### PR TITLE
lint templates & hyprland: update to 0.35.0 & libdrm: update to 2.4.120

### PR DESCRIPTION
**Pull request by zen0bit**
So teplates don't complain about linting in Void...

Just essential change

PS: release looks like build worked for me. (glibc, NO nvidia) But not yet runned hyprland..

### CODE REVIEW

**Comment by zen0bit** [comment]
> Does this really matter? This will never be submitted to void-packages while they continue being stubborn anyways.

Looks like 😢
Up to you

**Comment by D1zzl3D0p** [comment]
> Does this really matter? This will never be submitted to void-packages while they continue being stubborn anyways.

Well, I for one really appreciate the work you're doing. So thank you!

**Comment by Makrennel** [comment]
> (Maybe wallpaper will need same changes, mentioned in upstream release)

Not necessary, the install command I used just pulls anything ending with ".png" in the assets directory rather than "wall_*.png" like their makefile used.

Thanks for the help though.

**Comment by Makrennel** [comment]
... just for future note, I'd really rather people not revbump dependencies on this repo unnecessarily (i.e. libdrm) - I didn't notice, but now I have to keep the template around as void has only updated to 2.4.119 which is still compatible with Hyprland (for now). I specifically made the template only version 2.4.119 so that it would match the latest PR on void-packages.

**Pull request merged**
