### PR TITLE
Github build action and version 0.37.1

### PR DESCRIPTION
**Pull request by hesam-init**
Hey i created a build action to compile and release the packages on github to install the packages without any need to compile localy i tested version 35 and 36 and also 37 all of them works fine and compile process is nice and without any issue. You can download the latest build from my repo if you want or u can test the build action from this repo to make sure if its work or not. this action have some issues like version naming which i couldnt slove by my self. 

to install the packages on ur void machine u can use this command : 

`sudo xbps-install -R <packages-directory> hyprland hyprland-protocols hyprlang xdg-desktop-portal-hyprland`

if u find any problem with this flow tell me i will be happy to help ur project and solve the issues thank you <3

### CODE REVIEW

**Comment by soanvig** [comment]
I personally really like the idea, gonna test it today if I have time :-)

**Comment by soanvig** [comment]
Are you sure this is easily installable?

I downloaded your xbps files into /tmp, and tried to install using `sudo xbps-install -R . hyprland-nvidia hyprcursor hyprland-protocols hyprlang xdg-desktop-portal-hyprland` or `sudo xbps-install -R . hyprland-nvidia` or `sudo xbps-install -R . hyprland-nvidia`, and it complains about:

```
xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so.1'
```

(or similar)

Probably it's because I have my hyprland packages already installed.

**Comment by hesam-init** [comment]
> Are you sure this is easily installable?
> 
> I downloaded your xbps files into /tmp, and tried to install using `sudo xbps-install -R . hyprland-nvidia hyprcursor hyprland-protocols hyprlang xdg-desktop-portal-hyprland` or `sudo xbps-install -R . hyprland-nvidia` or `sudo xbps-install -R . hyprland-nvidia`, and it complains about:
> 
> ```
> xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so.1'
> ```
> 
> (or similar)
> 
> Probably it's because I have my hyprland packages already installed.



> Are you sure this is easily installable?
> 
> I downloaded your xbps files into /tmp, and tried to install using `sudo xbps-install -R . hyprland-nvidia hyprcursor hyprland-protocols hyprlang xdg-desktop-portal-hyprland` or `sudo xbps-install -R . hyprland-nvidia` or `sudo xbps-install -R . hyprland-nvidia`, and it complains about:
> 
> ```
> xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so.1'
> ```
> 
> (or similar)
> 
> Probably it's because I have my hyprland packages already installed.

yeah u have to remove the older version of hyprland to install it perfectly

**Comment by Makrennel** [comment]
As I mentioned with #36 I'm not against merging actions, but please don't bundle it with other commits unrelated to that - it just causes conflicts when other parts get updated before I get around to looking at the action.

That said, I'd be interested in figuring out a more robust system than I'm currently using with the kinda convoluted instructions to install/update hyprland, and not building locally would ideally be a part of that.

If you want to resubmit this action without the other parts please do, but I think we may have to figure out how to iron out some of these issues mentioned with needing to remove older versions to update.

**Pull request closed without merging**
