### PR TITLE
Bump hyprland to 0.37.1

### PR DESCRIPTION
**Pull request by zen0bit**
also:
Added hyprcursor
Bumped hyprlang

and shlibs...

### CODE REVIEW

**Comment by zen0bit** [comment]
Closes #42

**Comment by zen0bit** [comment]
- [x] bump
- [x] lint
- [x] build
- [] testing (In progress)

**Comment by zen0bit** [comment]
hyprcursor in my void-packages [action](https://github.com/oSoWoSo/VUR/actions/runs/8309639965) have some problem, not sure yet how to solve it..

cuted part:
```
=> hyprcursor-0.1.4_1: running do_build ...
[0/2] Re-checking globbed directories...
[1/10] Building C object CMakeFiles/hyprcursor_test_c.dir/tests/test.c.o
[2/10] Building CXX object CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor_c.cpp.o
[3/10] Building CXX object CMakeFiles/hyprcursor_test.dir/tests/test.cpp.o
[4/10] Building CXX object CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor.cpp.o
/builddir/hyprcursor-0.1.4/libhyprcursor/hyprcursor.cpp: In function 'cairo_status_t readPNG(void*, unsigned char*, unsigned int)':
/builddir/hyprcursor-0.1.4/libhyprcursor/hyprcursor.cpp:511:36: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
  511 |     std::memcpy(output, DATA->data + DATA->readNeedle, toRead);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
[5/10] Linking CXX shared library libhyprcursor.so.0.1.4
[6/10] Creating library symlink libhyprcursor.so.0 libhyprcursor.so
[7/10] Linking CXX executable hyprcursor_test
[8/10] Linking C executable hyprcursor_test_c
[9/10] Building CXX object hyprcursor-util/CMakeFiles/hyprcursor-util.dir/src/main.cpp.o
[10/10] Linking CXX executable hyprcursor-util/hyprcursor-util
=> hyprcursor-0.1.4_1: running do_check ...
[0/2] Re-checking globbed directories...
[0/1] Running tests...
Test project /builddir/hyprcursor-0.1.4/build
    Start 1: Test libhyprcursor in C++
1/2 Test #1: Test libhyprcursor in C++ ........***Exception: SegFault  0.14 sec

    Start 2: Test libhyprcursor in C
2/2 Test #2: Test libhyprcursor in C ..........***Exception: SegFault  0.09 sec


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.23 sec

The following tests FAILED:
	  1 - Test libhyprcursor in C++ (SEGFAULT)
	  2 - Test libhyprcursor in C (SEGFAULT)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /builddir/hyprcursor-0.1.4/build && /usr/libexec/xbps-src/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
=> ERROR: hyprcursor-0.1.4_1: do_check: '${make_check_pre} ${make_cmd} ${makejobs} ${make_check_args} ${make_check_target}' exited with 1
=> ERROR:   in do_check() at common/build-style/cmake.sh:129

Error: Process completed with exit code 1.
```

**Comment by Makrennel** [comment]
Why is there a vaguely named commit just called "lint" which adds a whole package that exists on void-packages and isn't an update?

**Comment by zen0bit** [comment]
Hyprpicker removed (since is not required)

**Comment by zen0bit** [comment]
> Why is there a vaguely named commit just called "lint" which adds a whole package that exists on void-packages and isn't an update?

Better now?

**Comment by ANA280044** [comment]
hyprpaper and xdg-desktop-portal-hyprland fails to install due to unresolvable shlib libhyprlang.so
`=> xbps-src: updating your system, confirm to proceed...
hyprpaper-0.6.0_1: broken, unresolvable shlib `libhyprlang.so'
xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so'
Transaction aborted due to unresolved shlibs.`

**Comment by zmeyka3310** [comment]
> hyprpaper and xdg-desktop-portal-hyprland fails to install due to unresolvable shlib libhyprlang.so `=> xbps-src: updating your system, confirm to proceed...`
> 
> `hyprpaper-0.6.0_1: broken, unresolvable shlib libhyprlang.so`
> 
> `xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib libhyprlang.so`
> 
> `Transaction aborted due to unresolved shlibs.`

happened to me when updating to 36. remove everything related and do a fresh install

**Comment by Makrennel** [comment]
Superseded by #50

**Pull request closed without merging**
