### PR TITLE
Build v0.43.0 using clang18

### PR DESCRIPTION
**Pull request by dom0**
Updated hyprland to 0.43.0 and all packages using the clang18 compiler.

These changes break the automatic compilation of plugins via hyprpm (it is still possible to compile them manually with some tricks)

### CODE REVIEW

**Comment by Makrennel** [comment]
I'll try testing this in the coming days, but if I can't get compilation on musl / aarch64 (if I can figure out how to test aarch64) working then I don't know if I'll merge this.

Also I'm not sure it's necessary to use Clang for all the templates if it's primarily Hyprland which needs it. Might just add a bunch of complexity in testing because xbps isn't really designed to use anything other than GCC to begin with.

As for hyprpm, I'm not really sure it's worth breaking that, I'll need some other opinions on that. Push comes to shove I could accept plugin build templates in this repo, but I would prefer to not add a ton of stuff that requires extra maintenance for which it is not certain whether or not it will be removed later.

**Comment by dom0** [comment]
I understand and share your point of view. these changes should only handle the transitory, until gcc is updated upstream. 

Unfortunately, in my opinion, updating hyprland to the latest releases at this time is particularly useful since after the remotion of wlroots many bugs have been fixed and just as many are emerging.

**Comment by Makrennel** [comment]
Tested on a musl host. Failed with error:

```
/builddir/hyprland-0.43.0/src/debug/Log.cpp:13:26: error: no member named 'native_handle' in 'std::basic_ofstream<char>'
   13 |     auto handle = logOfs.native_handle();
```

Any ideas?

**Comment by dom0** [comment]
> Tested on a musl host. Failed with error:
> 
> ```
> /builddir/hyprland-0.43.0/src/debug/Log.cpp:13:26: error: no member named 'native_handle' in 'std::basic_ofstream<char>'
>    13 |     auto handle = logOfs.native_handle();
> ```
> 
> Any ideas?

i'm not experienced in musl library but i'll try to investigate this error in the next weekend

**Comment by dom0** [comment]
Unfortunately, in addition to the one reported, there are other errors, some of which have already been fixed upstream. I'm working on needed patch and I'll update the pull request asap

**Comment by dom0** [comment]
I will shortly submit a new PR for v.044.0 with small C++ patches that compiles correctly with gcc13, restores musl build and supports plugins via hyrpppm

**Pull request closed without merging**
