### PR TITLE
Bump hyprland to 0.38

### LINKED ISSUE #42: hyprland 0.37.1 is out
Introducing new dependency:

### LINKED ISSUE #49: hyprland 0.38 is out

### PR DESCRIPTION
**Pull request by zen0bit**
Closes #42
Closes #49

### Lets test this
I am running it right now...

### CODE REVIEW

**Comment by zen0bit** [comment]
Build falling in hyprcursor TEST
```
=> hyprcursor-0.1.5_1: installing host dependencies: pkg-config-0.29.2_3 cairo-devel-1.18.0_1 gcc-13.2.0_2 hyprlang-0.5.0_1 cmake-bootstrap-3.27.6_2 ninja-1.11.1_4 ...
=> hyprcursor-0.1.5_1: installing target dependencies: glibc-devel-2.39_2 librsvg-devel-2.57.1_1 libzip-devel-1.10.1_1 ...
=> hyprcursor-0.1.5_1: running do-fetch hook: 00-distfiles ...
=> hyprcursor-0.1.5_1: fetching distfile 'v0.1.5.tar.gz' from 'https://github.com/hyprwm/hyprcursor/archive/refs/tags/v0.1.5.tar.gz'...
v0.1.5.tar.gz: [0B 0%] 50MB/s ETA: unknown
v0.1.5.tar.gz: 20KB [avg rate: 246MB/s]
=> hyprcursor-0.1.5_1: verifying checksum for distfile 'v0.1.5.tar.gz'... OK.
=> hyprcursor-0.1.5_1: running do-extract hook: 00-distfiles ...
=> hyprcursor-0.1.5_1: extracting distfile(s), please wait...
=> hyprcursor-0.1.5_1: running do-patch hook: 00-patches ...
=> hyprcursor-0.1.5_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> hyprcursor-0.1.5_1: running pre-configure hook: 01-override-config ...
=> hyprcursor-0.1.5_1: running pre-configure hook: 02-script-wrapper ...
=> hyprcursor-0.1.5_1: running do_configure ...
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'hyprlang>=0.4.2;libzip;cairo;librsvg-2.0'
--   Found hyprlang, version 0.5.0
--   Found libzip, version 1.10.1
--   Found cairo, version 1.18.0
--   Found librsvg-2.0, version 2.57.1
-- Configuring hyprcursor in Release
-- Checking for modules 'hyprlang>=0.4.0;libzip'
--   Found hyprlang, version 0.5.0
--   Found libzip, version 1.10.1
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /builddir/hyprcursor-0.1.5/build
=> hyprcursor-0.1.5_1: running pre-build hook: 02-script-wrapper ...
=> hyprcursor-0.1.5_1: running do_build ...
Not searching for unused variables given on the command line.
-- Checking for modules 'hyprlang>=0.4.2;libzip;cairo;librsvg-2.0'
--   Found hyprlang, version 0.5.0
--   Found libzip, version 1.10.1
--   Found cairo, version 1.18.0
--   Found librsvg-2.0, version 2.57.1
-- Configuring hyprcursor in Release
-- Checking for modules 'hyprlang>=0.4.0;libzip'
--   Found hyprlang, version 0.5.0
--   Found libzip, version 1.10.1
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /builddir/hyprcursor-0.1.5/build
[0/2] Re-checking globbed directories...
[1/10] Building C object CMakeFiles/hyprcursor_test_c.dir/tests/test.c.o
[2/10] Building CXX object CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor_c.cpp.o
[3/10] Building CXX object CMakeFiles/hyprcursor_test.dir/tests/test.cpp.o
[4/10] Building CXX object CMakeFiles/hyprcursor.dir/libhyprcursor/hyprcursor.cpp.o
[5/10] Linking CXX shared library libhyprcursor.so.0.1.5
[6/10] Creating library symlink libhyprcursor.so.0 libhyprcursor.so
[7/10] Linking CXX executable hyprcursor_test
[8/10] Linking C executable hyprcursor_test_c
[9/10] Building CXX object hyprcursor-util/CMakeFiles/hyprcursor-util.dir/src/main.cpp.o
/builddir/hyprcursor-0.1.5/hyprcursor-util/src/main.cpp: In function 'std::string spawnSync(const std::string&)':
/builddir/hyprcursor-0.1.5/hyprcursor-util/src/main.cpp:286:50: warning: ignoring attributes on template argument 'int (*)(FILE*)' [-Wignored-attributes]
  286 |     const std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                                  ^
[10/10] Linking CXX executable hyprcursor-util/hyprcursor-util
=> hyprcursor-0.1.5_1: running do_check ...
[0/2] Re-checking globbed directories...
[0/1] Running tests...
Test project /builddir/hyprcursor-0.1.5/build
    Start 1: Test libhyprcursor in C++
1/2 Test #1: Test libhyprcursor in C++ ........***Failed    0.01 sec
mgr is invalid

    Start 2: Test libhyprcursor in C
2/2 Test #2: Test libhyprcursor in C ..........***Failed    0.01 sec
mgr is invalid


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.02 sec

The following tests FAILED:
	  1 - Test libhyprcursor in C++ (Failed)
	  2 - Test libhyprcursor in C (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /builddir/hyprcursor-0.1.5/build && /usr/libexec/xbps-src/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
=> ERROR: hyprcursor-0.1.5_1: do_check: '${make_check_pre} ${make_cmd} ${makejobs} ${make_check_args} ${make_check_target}' exited with 1
=> ERROR:   in do_check() at common/build-style/cmake.sh:129
```

Any advice?

**Comment by soanvig** [comment]
https://github.com/hyprwm/hyprcursor/blob/main/tests/test.cpp#L16
https://github.com/hyprwm/hyprcursor/blob/main/libhyprcursor/hyprcursor.cpp#L267
https://github.com/hyprwm/hyprcursor/blob/main/libhyprcursor/hyprcursor.cpp#L221

a theme or something is missing maybe?

**Comment by soanvig** [comment]
@zen0bit I tried building locally hyprcursor from your PR, and after replacing these two lines:

```
distfiles="https://github.com/hyprwm/hyprcursor/archive/refs/tags/v${version}.zip"
checksum=b03660d9ac7a4b3c44ddeda4158584a00d176015c882d8e70f5c6bfccbff9366
```

I was able to build hyprcursor successfully.

Worth noting that I stayed on hyprcursor v0.1.5 (there is 0.1.7 alongside hyprland 0.38.1)

**Comment by zen0bit** [comment]
> @zen0bit I tried building locally hyprcursor from your PR, and after replacing these two lines:
> 
> ```
> distfiles="https://github.com/hyprwm/hyprcursor/archive/refs/tags/v${version}.zip"
> checksum=b03660d9ac7a4b3c44ddeda4158584a00d176015c882d8e70f5c6bfccbff9366
> ```
> 
> I was able to build hyprcursor successfully. Probably the issue was that you were using master branch?

0.1.5 and master I builded succesfully, just test phase fails.

And yes, I tried to solve test issue by using master

> Worth noting that I stayed on hyprcursor v0.1.5 (there is 0.1.7 alongside hyprland 0.38.1) I also started fresh void-packages if that means anything.

already trying 0.38.1

**Comment by zmeyka3310** [comment]
built from git, both hyprland, hyprlang and hyprcursor. everything working thus far

**Pull request merged**
