### PR TITLE
Packages version checker

### PR DESCRIPTION
**Pull request by hesam-init**
I wrote this script to check and compare package versions from local template files with the latest releases on github. 

image

### CODE REVIEW

**Comment by Makrennel** [comment]
> What about `sdbus-cpp` and `tomlplusplus`?

I'm pretty sure newer sdbus-cpp versions don't actually work with Hyprland

**Comment by Makrennel** [comment]
I tried the script but it doesn't seem to check aquamarine? I can see it in the list in the script, so I'm not sure what's up with that.

**Comment by hesam-init** [comment]
> I tried the script but it doesn't seem to check aquamarine? I can see it in the list in the script, so I'm not sure what's up with that.


i fixed the loop now it check all hyprland packages 

`
for package_dir in "$template_dir"/aquamarine/ "$template_dir"/hypr*/ "$template_dir"/xdg-desktop-portal-hyprland/
`

**Comment by Makrennel** [comment]
Cheers!

**Pull request merged**
