### PR TITLE
bump xdph to 1.3.1; bump hyprpaper to 0.6.0

### PR DESCRIPTION
**Pull request by flp5**
hi! some of this may be kind of janky because i am not too familiar with xbps-src

some notes:
- libdrm will need to be deleted when official repos update it
- tomlplusplus, hyprlang, sdbus-cpp are not separated into base pkg and devel
- `sysd.patch` for sdbus-cpp is essentially https://github.com/Kistler-Group/sdbus-cpp/pull/378, so should be removed with the next release
- i dont really understand the distinction between hostmakedepends and makedepends
- i didn't test this through much

### CODE REVIEW

**Comment by Makrennel** [comment]
Thanks, but I actually just finished updating Hyprland without noticing this PR. I haven't done xdph and hyprlang yet.

What is the sdbus-cpp patch necessary for?

I won't lie, I don't really get what the difference is myself.

**Comment by flp5** [comment]
hi, sdbus-cpp is for xdph. if you build sdbus-cpp without the patch, xdph fails to config saying there is no systemd

**Comment by flp5** [comment]
fixed merge conflicts

**Comment by Makrennel** [comment]
There's still some problems with this, like hyprland-nvidia is made useless, and libdrm doesn't need to include the patch and update files because they'll already be present when void-packages is cloned and instead we just want to copy the libdrm template on top of void's pre-existing template. I'll also be keeping libdrm on 2.4.119 because the most up to date PR on void-packages is only for 2.4.119, and if they merge that, and not 2.4.120, this repo will be stuck with the libdrm template lying around for longer than necessary. 

In future it would be better to split up individual changes into separate commits rather than making them all one big commit so that some commits can be reverted easily if one particular change to a file needs to removed. I'll just go ahead and manually fix it myself for now.

**Comment by flp5** [comment]
sure, sry for the inconvinience

**Comment by Makrennel** [comment]
> sure, sry for the inconvinience

No worries, thanks for your help.

**Comment by simvux** [comment]
@flp5 @Makrennel the dependency for hyprland in xdg-desktop-portal-hyprland was mispelled as "hyprlang" in this PR

**Comment by simvux** [comment]
oh hyprlang is an actual thing. I assumed it was a mistake because I'm now getting `No package 'hyprlang' found` when trying to install this on my other pc

**Pull request merged**
